name: Yangli's Blog
description:  Yangli's person blog.

sass:
  sass_dir: assets/css/_sass
  style: :compressed

# url: http://nadjetey.github.io

owner:
    name: Yang Li
    twitter: #
    github: BillLeecn
    disqus_shortname: yanglisblog

ga_id: UA-53442315-1
ga_username: auto

permalink: /:year/:month/:title/
timezone: Asia/Shanghai

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
