name: Yangli's Blog
description:  Yangli's person blog.

sass:
  sass_dir: assets/css/_sass
  style: :compressed

# url: http://nadjetey.github.io

owner:
    name: Yang Li
    twitter: #
    github: BillLeecn
    disqus_shortname: yanglisblog

ga_id: #
ga_username: #

permalink: /:year/:month/:title/
timezone: Asia/Shanghai

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
